name: CI
on:
  push:
    branches:
      - master
jobs:
  Documentation:
    permissions:
      contents: read
      pages: write
      id-token: write
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version:
          - 16
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Clone repository
        uses: actions/checkout@v4

      - name: Use Node ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm ci

      - name: Build documentation
        run: npm run build

      - name: Deploy documentation
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./docs

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
        id: deployment
